-- Link video nằm trên đơn. Ảnh nằm trong bucket order-images.
-- Chạy trong Supabase SQL Editor, rồi tải lại trang đơn hàng.

do $$
declare
  id_type text;
begin
  select c.data_type into id_type
  from information_schema.columns c
  where c.table_schema = 'trangway'
    and c.table_name = 'orders'
    and c.column_name = 'id';

  execute 'alter table trangway.orders add column if not exists video_url text';

  if to_regclass('trangway.order_images') is null then
    execute format(
      'create table trangway.order_images (
         id bigint generated by default as identity primary key,
         order_id %s not null references trangway.orders (id) on delete cascade,
         storage_path text not null,
         sort_order integer not null default 0,
         created_at timestamptz not null default now()
       )',
      case when id_type = 'integer' then 'integer' else 'bigint' end
    );
  end if;

  execute 'create index if not exists order_images_order_id_idx on trangway.order_images (order_id, sort_order)';
end $$;

grant select, insert, update, delete on trangway.order_images to anon, authenticated, service_role;
grant usage, select on sequence trangway.order_images_id_seq to anon, authenticated, service_role;

insert into storage.buckets (id, name, public)
values ('order-images', 'order-images', true)
on conflict (id) do update set public = true;

drop policy if exists order_images_select on storage.objects;
drop policy if exists order_images_insert on storage.objects;
drop policy if exists order_images_update on storage.objects;
drop policy if exists order_images_delete on storage.objects;

create policy order_images_select on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'order-images');

create policy order_images_insert on storage.objects
  for insert to anon, authenticated
  with check (bucket_id = 'order-images');

create policy order_images_update on storage.objects
  for update to anon, authenticated
  using (bucket_id = 'order-images');

create policy order_images_delete on storage.objects
  for delete to anon, authenticated
  using (bucket_id = 'order-images');

notify pgrst, 'reload schema';
